export const START_REQUEST = '@START_REQUEST';
export const STOP_REQUEST = '@STOP_REQUEST';

export const PARTNER_REQUEST = 'PARTNER_REQUEST';
export const PARTNER_FULFILL = 'PARTNER_FULFILL';
export const PARTNER_REJECT = 'PARTNER_REJECT';
